### ISSUE TITLE
Color change

### ISSUE THREAD

**Issue by Erdbeersahne** [p3lim-wow/oUF_P3lim#10]
I have questions about oUF P3lim. But my English is not good, sorry.
How can I change the color?
How can I disable oUF_Experience?

Thank you and best regards

**Comment by p3lim** [comment]
A more appropriate place to ask this is on the [WoWInterface forums](http://www.wowinterface.com/forums/forumdisplay.php?f=87).

You can disable oUF_Experience by removing [these lines](https://github.com/p3lim-wow/oUF_P3lim/blob/80000.31-Release/oUF_P3lim.lua#L282-L299).

For colors you have to be a bit more specific, there are many elements with different colors.

**Comment by Erdbeersahne** [comment]
Thank you! 
I would like to have gray or class colors for the main frame not purple, like at the moment. Otherwise, the UI is perfect. The idea with the magic stroke is outstanding!

**Comment by Erdbeersahne** [comment]
Sorry for bad english

**Comment by p3lim** [comment]
This is where I set the health bar colors: https://github.com/p3lim-wow/oUF_P3lim/blob/80000.31-Release/oUF_P3lim.lua#L500

Just replace the `(1/3, 1/3, 1/3)` with whatever you want, e.g. `(1, 0, 0)` for solid red.  
Class colors are harder because I've replaced the health update function. Ask on the forums for help with that one.

**Comment by Erdbeersahne** [comment]
Hi Adrian, ich dachte, ich schreibe einfach mal deutsch in der Hoffnung, du
kannst das verstehen. Ich nutze seit Jahren in wow dein Addon weil es sehr
minimal ist und ich mich daran gewöhnt habe. Meine Frage ist, machst du
auch eine UI für die wow classic Version, die heute startet? Ich wäre sher
interessiert!.
Beste Grüße, Erdbeersahne

Am Sa., 28. Juli 2018 um 21:12 Uhr schrieb Adrian L Lange <
notifications@github.com>:

**Comment by p3lim** [comment]
I'm sorry, I dont speach german.

**Comment by Erdbeersahne** [comment]
Hey Adrian, I'm not a problem. I just wanted to ask if you build an addon
for wow classic?
Best regards

Am Mo., 26. Aug. 2019 um 23:02 Uhr schrieb Adrian L Lange <
notifications@github.com>:

**Comment by Erdbeersahne** [comment]
Hey Adrian, I'm not a problem. I just wanted to ask if you build an addon
for wow classic?
Best regards

Am Di., 27. Aug. 2019 um 00:10 Uhr schrieb Yanek Winter <
yanek.winter@gmail.com>:

**Comment by p3lim** [comment]
I have no plans to support classic in any of my addons, nor make new ones for it.
