### ISSUE TITLE
russian language

### ISSUE THREAD

**Issue by RUSTARD** [p3lim-wow/oUF_P3lim#2]
Hello. im russian and i use ur addon.Its very comfortable, but it have a little trouble. Ur addon don't understand russian language. Instead of russian nicks or NPC names i have only "???????????????" Version 6.1.2. Plz make a fix. From russia with love.

**Comment by p3lim** [comment]
The font used in this addon has very poor character support, and I won't replace it for my own use.
I will however see if I can default to a different font in scenarios such as yours.
