### ISSUE TITLE
Show hide the runes when out of combat and fully charged

### ISSUE THREAD

**Issue by johnsolver** [p3lim-wow/oUF_P3lim#5]
Is there a way to hide the runes when they are all fully charged and you're out of combat, and show when either in combat or not fully charged?

**Comment by p3lim** [comment]
More appropriate place to ask this is on the WoWInterface forums, but what the heck.

You add a PostUpdate to the Runes element and hide/show them (using alpha) based on the [6th parameter (runeReady)](https://github.com/haste/oUF/blob/441ee4be0d1140f7861e416609760cf7003a36be/elements/runebar.lua#L112).

As for my layout supporting this I would like to refer you to the locked comment section on the [project page](http://wowinterface.com/downloads/info8455#comments) on WoWInterface.
