### ISSUE TITLE
invalid tag areanaspec

### ISSUE THREAD

**Issue by crzyface** [p3lim-wow/oUF_P3lim#7]
This happens at login

Version: 70100.26-Release

Message: Attempted to use invalid tag [arenaspec].
Time: 04/14/17 08:18:31
Count: 1
Stack: [C]: in function `error'
...erface\AddOns\oUF_P3lim\embeds\oUF\elements\tags.lua:593: in function `Tag'
Interface\AddOns\oUF_P3lim\oUF_P3lim.lua:429: in function <Interface\AddOns\oUF_P3lim\oUF_P3lim.lua:427>
(tail call): ?
Interface\AddOns\oUF_P3lim\embeds\oUF\ouf.lua:263: in function <Interface\AddOns\oUF_P3lim\embeds\oUF\ouf.lua:193>
(tail call): ?
Interface\AddOns\oUF_P3lim\embeds\oUF\ouf.lua:558: in function `Spawn'
Interface\AddOns\oUF_P3lim\oUF_P3lim.lua:605: in function `func'
Interface\AddOns\oUF_P3lim\embeds\oUF\factory.lua:20: in function <Interface\AddOns\oUF_P3lim\embeds\oUF\factory.lua:16>
(tail call): ?

Locals: (*temporary) = "Attempted to use invalid tag [arenaspec]."

**Comment by p3lim** [comment]
It's a leftover tag from a feature I was working on for oUF, you'll only see that error once and it won't affect anything.

**Comment by p3lim** [comment]
Fixed in https://github.com/p3lim-wow/oUF_P3lim/commit/e888de7cc4864e55a23c3f899598be976c910c12#diff-b63f905d62fb7d1ffdc9150d23d704bcL463
