### ISSUE TITLE
create font string

### ISSUE THREAD

**Issue by crzyface** [p3lim-wow/oUF_P3lim#9]
this error only pops up on startup

Message: Interface\AddOns\oUF_P3lim\oUF_P3lim.lua:471: <unnamed>:CreateFontString(): Couldn't find inherited node "oUF_P3limFont"
Time: 11/10/17 19:16:17
Count: 1
Stack: Interface\AddOns\oUF_P3lim\oUF_P3lim.lua:471: <unnamed>:CreateFontString(): Couldn't find inherited node "oUF_P3limFont"
[C]: ?
[C]: in function `CreateFontString'
Interface\AddOns\oUF_P3lim\oUF_P3lim.lua:471: in function <Interface\AddOns\oUF_P3lim\oUF_P3lim.lua:470>
(tail call): ?
Interface\AddOns\oUF_P3lim\embeds\oUF\ouf.lua:304: in function <Interface\AddOns\oUF_P3lim\embeds\oUF\ouf.lua:234>
(tail call): ?
Interface\AddOns\oUF_P3lim\embeds\oUF\ouf.lua:660: in function `Spawn'
Interface\AddOns\oUF_P3lim\oUF_P3lim.lua:646: in function `func'
Interface\AddOns\oUF_P3lim\embeds\oUF\factory.lua:20: in function <Interface\AddOns\oUF_P3lim\embeds\oUF\factory.lua:16>
(tail call): ?

Locals:

**Comment by p3lim** [comment]
https://github.com/p3lim-wow/oUF_P3lim/commit/99c4680102e2710a2dca988d98104eadb7a62d80
